export default {
  orderNo: '55122336521',
  totalCap: '壹佰元整',
  table: [
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品01',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品02',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品03',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品04',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品05',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品06',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品07',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品08',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品09',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品10',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品11',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
    {
      shopName: '王者烘焙万达店',
      barcode: '2O22010100110',
      productName: '测试商品01',
      skuName: '',
      productionDate: '',
      product: '测试商品12',
      number: 1,
      unit: '个',
      productPrice: '13.6',
      subTotal: '13.6',
    },
  ],
}
